name: Lint (Trunk)
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install --global pnpm@latest
      - name: Install dev dependencies
        run: pnpm install --dev
      - name: Install dependencies
        run: pnpm install
      - name: Analyze with ESLint
        run: pnpm lint
